---

- name: create spark master systemd service file
  template:
    src: systemd/spark-master.service.j2
    dest: /etc/systemd/system/spark-master.service
  notify:
  - reload systemd
  - restart spark-master

- name: start spark master
  service:
    name: spark-master
    state: started
    enabled: yes
