---
- name: Restart spark-master
  ansible.builtin.service:
    name: spark-master
    state: restarted
  when: spark_master is defined and spark_master

- name: Restart spark-historyserver
  ansible.builtin.service:
    name: spark-historyserver
    state: restarted
  when: spark_historyserver is defined and spark_historyserver

- name: Restart spark-slave
  ansible.builtin.service:
    name: spark-slave
    state: restarted
  when: spark_slave is defined and spark_slave

- name: Restart spark-thriftserver
  ansible.builtin.service:
    name: spark-thriftserver
    state: restarted
  when: spark_thriftserver is defined and spark_thriftserver

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
